cipher_text = """RCXQN AIXPC FQFEF IKFJX RMJMQ RMTSQ QCXPX NPXQX KRQFK MIAMS QKMWA MSQFK AJFGV CALCX UXPYM KXCFQ RXKQR MLPSQ CSKIX PTMMR FHFAK QRRCA QQSJJ FPYUX PIALR
RCXME QXPUX PQXRQ RCXEX FQRQA KISQR PYARQ RFGXK RFQFV XFUXP ARQVA GAKXQ QAKRC XLCFQ XARQR PFHAL KSNRA FGQFK IMRCX PLCFP FLRXP AQRAL QMTHP XFRAK RXPXQ
RYXQR CXQNA IXPAQ VXGGV MPRCQ RSIYA KHFNF PRTPM JFKYQ LAXKR ATALP XFQMK QESRQ CXAQQ FAIRM EXNMA QMKMS QFKIR CFRAQ CXPLP AJXFK IRCXN PAJFP YLFSQ XMTRC
XPXNS HKFKL XVCXP XVARC QCXAK QNAPX QSQNM AQMKM SQAFH PXXAT EYRCF RVXSK IXPQR FKIRC FRRCX FKAJF GAQFP JXIVA RCRVM TFKHQ VCALC LFSQX RCXAJ JXIAF RXIXF
RCMTR CXGAR RGXUA LRAJQ VCALC ARLFR LCXQE SRRCX PXAQF VAIXI ATTXP XKLXE XRVXX KDAGG AKHFJ AIHXF KICFP JAKHF JFKCM VXUXP AJJXI AFRXA KARQX TTXLR QSNMK
RCXAK QXLRX KRFKH GXIAK RCXTF RFGVX ERCXQ NAIXP QNMAQ MKAQK MRQXP AMSQT MPSQF KILFS QXQGX QQAKL MKUXK AXKLX RCFKF HKFRE ARXRC FRFRG XFQRA QVCFR VXLFK
QFTXG YQFYF QPXHF PIQRC XHPXF RJFBM PARYM TRCXQ NAIXP QMTMS PPXHA MKQKX UXPRC XGXQQ FTXVF PXRME XTXFP XIFKI TMPXJ MQRFJ MKHRC XQXAQ RCXJF GJAHK FRRXR
CXRXP PMPMT RCXLM PQALF KNXFQ FKRPY ACFUX QXXKC XPQXR RGXAK RCXTS PPMVQ GFYMS RCXPV XEFKI PSQCE MGIGY FRAKQ XLRQG FPHXP RCFKC XPQXG TACFU XFIJA PXICX
PHFPE MTEGF LDUXG UXRQN XLDGX IVARC LFPJA KXPXI FEMUX FGGAC FUXCX FPIJM QRIAQ OSAXR AKHQR MPAXQ RMGIF EMSRC XPFPM SKIFB FLLAM FKIEM KATFL AMCXP EARXA
QPXNS RXIUX PYIFK HXPMS QQMJX RAJXQ JMPRF GRCXL MSKRP YJFKI XLGFP XQRCA QTMPF TFLRF KIRCX IMLRM PIMXQ KMRFG VFYQI FPXIX KYARA KRCXK XAHCE MSPCM MIMTN
SBFSI KMRTF PTPMJ FUAHK MKRCX CFPUX QRXPQ QNXFD VARCI PXFIM TRCXP AIAMK GSHSE PXTAP QRMEQ XPUXI EYGXM KISTM SPAKR CXLFR FGMKA FKJMS KRFAK QFLLM PIAKH
RMRCX JCXPE ARXVM SGIGX FIRMQ XPAMS QFLLA IXKRQ RCXAR FGAFK QCFUX EXQRM VXIFE FIPXN SRFRA MKMKR CXRFP FKRSG FVCMN PMISL XQLMK USGQA MKQFK ITPXK ZAXII
FKLXQ AKRCX NXPQM KQRSK HEYCX PRMLM NXVAR CRFPF KRAQJ RCXKF JXHAU XKRMR CXIAQ XFQXR CFRTM GGMVQ MKRCX EARXM TRCXA RFGAF KQNAI XPYMS JSQRC FUXPX LMSPQ
XRMJS QALRC XMKGY XTTAL FLAMS QPXJX IYQMR CXYRX GGSQQ NXLAF GRSKX QCFUX EXXKK MRXIR CMQXO SALDX QRRMF TTMPI PXGAX TRCXP XAQJX IALFG LCMPX MHPFN CYJXI
ALFGJ SQALF KICFU XVXKM RRCXR FPXKR XGGFF GAUXG YFKIK AJEGX IFKLX EXOSX FRCXI RMSQN XPCFN QEYRC XCXFG AKHFP RMTRC XLFGF EPAFK NXFQF KRJSQ RVXRF DXRCX
QXOSX XPRCA KHQQX PAMSQ GYMPG FSHCF RRCXJ TPMJR CXGAR RGXRC FRACF UXQXX KACXQ ARFRX RMNPM KMSKL XFKMN AKAMK KMRCA KHRXG GQSQR CFRRC XEARX MTRCX RFPFK
RSGFJ FYKMR NPMUM DXAKV XFDFK IUXPY AJNPX QQAMK FEGXN XMNGX FKXPU MSQIA QMPIX PVCAL CJSQA LVAGG PXGAX UXKMR CAKHR XGGQS QRCFR FNPMT SQXNX PQNAP FRAMK
PXQSG RAKHT PMJFU XPYXK XPHXR ALIFK LXAQK MRGAD XGYRM IAJAK AQCRC XIAQL MJTMP REYIA JAKAQ CAKHR CXLFS QXMTR CXFAG JXKRQ MTFPT PMJGF SHCAK HAPXT GXLRF
KIXKO SAPXV CXKRC XLFGF EPAFK NXFQF KRRFG DQRMJ XMTCA QRFPF KRSGF RCXNS BFSIP XFNXP MTCAQ RCXPA IAMKG SHSEP XRCXL MPQAL FKCSQ EFKIJ FKMTC AQJFG JAHKF
RRXRC MQXQN AIXPQ JAHCR XFQAG YIXQX PUXFR GXFQR NFPRG YRCXA PRXPP AEGXP XNSRF RAMK"""

alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
key = "IZHKBALGDMNCOPJRSTUFVWXEYQ"


def get_index(letter):
    return alphabet.index(letter)


plain_text = ""
for char in cipher_text:
    if char.isalpha():
        plain_text += key[get_index(char)]
    else:
        plain_text += char

print(plain_text)
